title = "Chainbound"
baseURL = "https://www.chainbound.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false                          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""                  # add your tracking id

[params]
author = "Chainbound"
description = "Chainbound is a research and development organization building optimized infrastructure and networking tools for blockchains"
favicon = "favicon.svg"                                                                                                                      # path to a .ico to use as favicon
logo = "favicon.svg"
# [params.footer]
# text = "Hugo theme by Olivier Roques"
# url = "https://github.com/ojroques/hugo-researcher"
[params.style] # appearance options (can be omitted)
fontFamily = "Inconsolata"
fontSize = "14pt"
pageWidth = "750px"
avatarSize = "90px"
colorBlack = "#222222"
colorRed = "#dc3545"
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/chainbound_"
[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/chainbound"

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
name = "About"
url = "/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown files
